[package]
name = "KitsuneOS"
version = "0.1.0"
edition = "2024"
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
[[bin]]
name = "KitsuneOS"
test = false
bench = false
[dependencies]
mutex = "1.0.2"
simple-psf = "0.1.2"
spin = "0.10.0"
uefi = "0.36.1"
